### ISSUE TITLE
Fix Failing Tests

### ISSUE THREAD

**Issue by jdevries3133** [jdevries3133/jackdevries.com#3]
4 unit tests are failing. This is the output I get on my machine:

```
  4 failing

  1) Node Debug Adapter etc
       get loaded scripts
         returns all scripts:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(loadedSources.find(source => source.path === expectedPath))

      at assertHasSource (out/test/adapter.test.js:311:13)
      at /Users/johndevries/.vscode_node_debug/out/test/adapter.test.js:323:13
      at Generator.next (<anonymous>)
      at fulfilled (out/test/adapter.test.js:9:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) Breakpoints
       setBreakpoints in TypeScript
         still resolves sourcemap paths when they are absolute local paths:
     Error: Command failed: npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code 2
npm ERR! path /Users/johndevries/.vscode_node_debug/testdata/sourcemaps-local-paths
npm ERR! command failed
npm ERR! command sh -c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johndevries/.npm/_logs/2022-06-29T02_17_42_585Z-debug-0.log

      at ChildProcess.exithandler (node:child_process:399:12)
      at ChildProcess.emit (node:events:520:28)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

  3) Breakpoints
       setExceptionBreakpoints
         should not stop on exception in <node_internals> when skipFiles is used:

      AssertionError [ERR_ASSERTION]: 'exception' == 'breakpoint'
      + expected - actual

      -exception
      +breakpoint

      at /Users/johndevries/.vscode_node_debug/node_modules/vscode-debugadapter-testsupport/lib/debugClient.js:264:20
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Promise.all (index 2)

  4) Stepping
       skipFiles
         can skip node internal files using <node_internals>:

      AssertionError [ERR_ASSERTION]: 'step' == 'breakpoint'
      + expected - actual

      -step
      +breakpoint

      at /Users/johndevries/.vscode_node_debug/node_modules/vscode-debugadapter-testsupport/lib/debugClient.js:264:20
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Promise.all (index 1)
```

**Comment by jdevries3133** [comment]
oops, wrong repo!
